// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKEmxSfmBiaDrR5Gt2692A94FUQ6_Odo',
    appId: '1:1058575856268:android:f76aa41e8df4b37d7281a9',
    messagingSenderId: '1058575856268',
    projectId: 'fireship-flutter-a9f66',
    storageBucket: 'fireship-flutter-a9f66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArBmN6Rg6uyPHjQ7e5qGyzCRHNADt5Iik',
    appId: '1:1058575856268:ios:04699796d63fddb27281a9',
    messagingSenderId: '1058575856268',
    projectId: 'fireship-flutter-a9f66',
    storageBucket: 'fireship-flutter-a9f66.appspot.com',
    androidClientId: '1058575856268-e1et3jadbsc8f8eq1lgi8gjc72pjo6q3.apps.googleusercontent.com',
    iosClientId: '1058575856268-8snh9hu6tb2g0etu1pm4a5g02u5a3coa.apps.googleusercontent.com',
    iosBundleId: 'com.kihyeonkwon.quizapp',
  );
}
